global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  # StatsD Exporter (for airflow or mlflow metrics via StatsD)
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']  # or 'localhost:9102' if local

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

